namespace CacheKeys {
    export const PATIENTS_CACHE_KEY = "PATIENTS_CACHE_KEY";
    export const PATIENT_CACHE_KEY = "PATIENT_CACHE_KEY";

    export const STAFFS_CACHE_KEY = "STAFFS_CACHE_KEY";
    export const STAFF_CACHE_KEY = "STAFF_CACHE_KEY";
    export const PATIENT_CHAT_LIST_CACHE_KEY = "PATIENT_CHAT_LIST_CACHE_KEY";

    export const STAFF_CHAT_LIST_CACHE_KEY = "STAFF_CHAT_LIST_CACHE_KEY";
    export const ROLE_CACHE_KEY = "ROLE_CACHE_KEY";
    export const FLAG_CACHE_KEY = "FLAG_CACHE_KEY";

    export const IMPLANT_CATEGORY_CACHE_KEY = "IMPLANT_CATEGORY_CACHE_KEY";

    export const IMPLANT_CACHE_KEY = "IMPLANT_CACHE_KEY";

    export const EQUIPMENT_CATEGORY_CACHE_KEY = "EQUIPMENT_CATEGORY_CACHE_KEY";
    export const EQUIPMENT_CACHE_KEY = "EQUIPMENT_CACHE_KEY";

    export const TEMPLATES_CACHE_KEY = "TEMPLATES_CACHE_KEY";
    export const SURGERIES_CACHE_KEY = "SURGERIES_CACHE_KEY";
    export const SURGERY_CACHE_KEY = "SURGERY_CACHE_KEY";

    export const MBS_ITEM_CACHE_KEY = "MBS_ITEM_CACHE_KEY";
    export const BOOKINGS_CACHE_KEY = "BOOKINGS_CACHE_KEY";
    export const BOOKING_DETAIL_CACHE_KEY = "BOOKING_DETAIL_CACHE_KEY";

    export const CALENDAR_CACHE_KEY = "CALENDAR_CACHE_KEY";
    export const CALENDAR_EVENT_CACHE_KEY = "CALENDAR_EVENT_CACHE_KEY";
    export const EVENT_CACHE_KEY = "EVENT_CACHE_KEY";

    export const MONTHLY_CALENDAR_CACHE_KEY = "MONTHLY_CALENDAR_CACHE_KEY";
    export const SURGEONS_CACHE_KEY = "SURGEONS_CACHE_KEY";
}

export default CacheKeys;
